import type { Metadata } from "next";
import "./globals.css";
import ReduxStoreProvider from "@/Redux/ReduxProvider";
export const metadata: Metadata = {
  title: "High School",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased `}
      >
       
        <ReduxStoreProvider>
          {children}
        </ReduxStoreProvider>
      </body>
    </html>
  );
}
